/*
 * 统计有SM30的自建表记录数
 */
-- 存在一些问题: 当自建表中存在主键 mandt 时，无法统计 SE16N 自建表记录数
SELECT
    SS.SCHEMA_NAME,
    SS.TABLE_NAME,
    SUM(SS.RECORD_COUNT) AS RECORDS
    FROM SYS.M_TABLES AS SS 
    INNER JOIN TVDIR AS TV ON TV.TABNAME = SS.TABLE_NAME
    WHERE SS.TABLE_NAME LIKE 'Z%'
    GROUP BY SS.SCHEMA_NAME, SS.TABLE_NAME
    ORDER BY SS.SCHEMA_NAME, RECORDS DESC